#!/bin/bash

sudo apt install curl

type -p curl >/dev/null || (sudo apt update && sudo apt install curl -y)
curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg \
&& sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg \
&& echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
&& sudo apt update \
&& sudo apt install gh -y

STTY_PRESENT=$(grep "stty -ixon" ~/.bashrc)
BIND_PRESENT=$(grep "bind -r '\\\C-s'" ~/.bashrc)

if [ -z "$STTY_PRESENT" ]; then
  echo "writing 'stty -ixon' to .bashrc..."
  echo "stty -ixon" >> ~/.bashrc
fi
if [ -z "$BIND_PRESENT" ]; then
  echo "writing 'bind -r '\C-s'' to .bashrc..."
  echo "bind -r '\C-s'" >> ~/.bashrc
fi
VIMRC_FILE=~/.vimrc
if test -f "$VIMRC_FILE"; then
    echo
else
    cp src/vimrc ~/.vimrc
    echo "copied src/vimrc to .vimrc"
fi

